name             'jenkins_cookbook'
maintainer       'Ryan Garaygay'
maintainer_email 'ryan.garaygay@gmail.com'
license          'all_rights'
description      'Installs/Configures jenkins_cookbook'
long_description 'Installs/Configures jenkins_cookbook'
version          '0.1.0'
depends          'apt'
depends          'git'
depends          'jenkins', '~> 2.2.2'
